package parser.nodes

import manager.CodeLocation

/**
 * A node in the AST generated by the parser. These nodes do not contain semantic information but are just
 * the original source code expressed as a syntax tree.
 *
 * @param codeLocation the location of the first character of the source code that this parse node represents.
 */
abstract class BaseParseNode(val codeLocation: CodeLocation)